package com.pojo;

import java.util.ArrayList;
import java.util.List;

public class TSysMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.menu_name
     *
     * @mbg.generated
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.menu_url
     *
     * @mbg.generated
     */
    private String menuUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.ordered
     *
     * @mbg.generated
     */
    private Integer ordered;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_menu.new_column
     *
     * @mbg.generated
     */
    private Integer newColumn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.id
     *
     * @return the value of t_sys_menu.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.id
     *
     * @param id the value for t_sys_menu.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.menu_name
     *
     * @return the value of t_sys_menu.menu_name
     *
     * @mbg.generated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.menu_name
     *
     * @param menuName the value for t_sys_menu.menu_name
     *
     * @mbg.generated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.menu_url
     *
     * @return the value of t_sys_menu.menu_url
     *
     * @mbg.generated
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.menu_url
     *
     * @param menuUrl the value for t_sys_menu.menu_url
     *
     * @mbg.generated
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.parent_id
     *
     * @return the value of t_sys_menu.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.parent_id
     *
     * @param parentId the value for t_sys_menu.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.ordered
     *
     * @return the value of t_sys_menu.ordered
     *
     * @mbg.generated
     */
    public Integer getOrdered() {
        return ordered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.ordered
     *
     * @param ordered the value for t_sys_menu.ordered
     *
     * @mbg.generated
     */
    public void setOrdered(Integer ordered) {
        this.ordered = ordered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_menu.new_column
     *
     * @return the value of t_sys_menu.new_column
     *
     * @mbg.generated
     */
    public Integer getNewColumn() {
        return newColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_menu.new_column
     *
     * @param newColumn the value for t_sys_menu.new_column
     *
     * @mbg.generated
     */
    public void setNewColumn(Integer newColumn) {
        this.newColumn = newColumn;
    }

    public List<TSysMenu> getChildren() {
        return children;
    }

    public void setChildren(List<TSysMenu> children) {
        this.children = children;
    }

    private List<TSysMenu> children = new ArrayList<>();

    public TSysMenu getParent() {
        return parent;
    }

    public void setParent(TSysMenu parent) {
        this.parent = parent;
    }

    private TSysMenu parent;
}